amazon/Models/productReponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using amazon.AWSE;
using System.Configuration;

namespace amazon.Models
{
    public class productReponse
    {
        public IEnumerable<Item> GetProducts(string sona, int leht)
        {
            AWSECommerceServicePortTypeClient ecs = new AWSECommerceServicePortTypeClient();
            ItemSearchRequest paring = new ItemSearchRequest();
            paring.ResponseGroup = new string[] { "ItemAttributes,OfferSummary" };
            paring.SearchIndex = "All";
            paring.Keywords = sona;
            paring.ItemPage = String.Format("{0}", leht);
            paring.MinimumPrice = "0";

            ItemSearch otsi = new ItemSearch();
            otsi.Request = new ItemSearchRequest[] { paring };
            otsi.AWSAccessKeyId = ConfigurationManager.AppSettings["accessKeyId"];
            otsi.AssociateTag = ConfigurationManager.AppSettings["associateTag"];
            ItemSearchResponse vastus = ecs.ItemSearch(otsi);

            if (vastus == null)
            {
                throw new Exception("Server Error - didn't get any reponse from server!");
            }
            else if (vastus.OperationRequest.Errors != null)
            {
                throw new Exception(vastus.OperationRequest.Errors[0].Message);
            }
            else if (vastus.Items[0].Item == null)
            {                
                throw new Exception("Didn't get any items!Try agen with different keyword.");
            }
            else
            {
                return vastus.Items[0].Item;
            }
        }
    }
}

amazon/Controllers/PeaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using amazon.AWSE;
using amazon.Models;
using amazon.Currency;

namespace amazon.Controllers
{
    public class PeaController : Controller
    {
        private const int postlehel = 13;
        static IEnumerable<Item> kogu;
        public ActionResult Index()
        {            
            return View();
        }
        [HttpPost]
        public ActionResult Index(string sona)
        {
            if (kogu == null)
            {
                try
                {
                    andmed(sona);
                }
                catch (Exception e)
                {
                    ViewBag.error = e.Message;
                    return View();
                }
            }
            return RedirectToAction("Otsing");
        }
        public ActionResult Otsing(int? id)
        {
            ViewBag.Currency = Enum.GetNames(typeof(Currency.Currency));            
            int lehenumber = id ?? 0;
            
            IEnumerable<Item> products = (from item in kogu
                                          select item).Skip(lehenumber * postlehel).Take(postlehel + 1);
            ViewBag.IsPreviousLinkVisible = lehenumber > 0;
            ViewBag.IsNextLinkVisible = products.Count() > postlehel;
            ViewBag.LeheNumber = lehenumber;

            return View(products.Take(postlehel));
        }
        public double Currency(string from, string to)
        {
            CurrencyConvertorSoapClient client = new CurrencyConvertorSoapClient();
            var rate = client.ConversionRate((amazon.Currency.Currency)Enum.Parse(typeof(amazon.Currency.Currency), from),
                (amazon.Currency.Currency)Enum.Parse(typeof(amazon.Currency.Currency), to));
            return rate;
        }
        public ActionResult BackToMain()
        {
            kogu = null;
            return RedirectToAction("Index");
        }
        static void andmed(string sona)
        {
            productReponse vastus = new productReponse();
            for (int i = 1; i <= 5; i++)
            {
                IEnumerable<Item> itempage = vastus.GetProducts(sona, i);
                if (kogu == null)
                {
                    kogu = itempage;
                }
                else
                {
                    kogu = kogu.Concat(itempage);
                }
            }
        }
    }
}

amazon/Views/Pea/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h2>Amazon product search:</h2>

@{
    using(Html.BeginForm("Index","Pea",FormMethod.Post))
    {
        <input id="otsing" type="text" name="sona" />
        <input id="saada" type="submit" value="Search" />
    }
}
@{
    if(ViewBag.error != null)
    {
        <div class="alert-message error">
            <p>@ViewBag.error</p>
        </div>
    }
}

amazon/Views/Pea/Otsing.cshtml
@model IEnumerable<amazon.AWSE.Item>
@{
    ViewBag.Title = "Otsing";
}
<script src="~/Scripts/CurrencyChange.js"></script>
<h2>Otsing</h2>
@{
    bool isPreviousLinkVisible = ViewBag.IsPreviousLinkVisible ?? false;
    bool isNextLinkVisible = ViewBag.IsNextLinkVisible ?? false;
    var item1 = Model.First();
}
<select id="currency" name="currency" onchange="changePrices(this)">
    @foreach (var currency in ViewBag.Currency)
    {
        if (item1.OfferSummary != null && item1.OfferSummary.LowestNewPrice != null 
            && currency == item1.OfferSummary.LowestNewPrice.CurrencyCode)
        {
            <option value="@currency" selected>@currency</option>
        }
        else
        {
            <option value="@currency">@currency</option>
        }
    }
    </select> 
@{
    <div class="CSSTableGenerator">
        <table>
            <tr>
                <td>Title</td>
                <td>Price</td>
            </tr>
            @foreach (var item in Model)
            {
                string price;
                if (item.OfferSummary == null)
                {
                    price = "Unavailable";
                }
                else if (item.OfferSummary.LowestNewPrice == null)
                {
                    price = "Unavailable";
                }
                else
                {
                    price = item.OfferSummary.LowestNewPrice.FormattedPrice;
                    price = price.Replace("$", string.Empty);
                    price = price.Replace(",", string.Empty);
                }

                <tr><td id="item">@item.ItemAttributes.Title</td><td class="price">@price</td></tr>

            }
        </table>
    </div>
}
@if (isPreviousLinkVisible)
{
    <a id="previousLink" href="@Href("~/Pea/Otsing/" + (ViewBag.LeheNumber - 1))">&lt; Previous Page</a>
}

@if (isNextLinkVisible)
{
    <a id="nextLink" href="@Href("~/Pea/Otsing/" + (ViewBag.LeheNumber + 1))">Next Page &gt;</a>
}
<br />
&lt;@Html.ActionLink("Tagasi otsingu lehele.", "BackToMain", "Pea", null, new { id= "tagasi"})

amazon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Amazon Product Advertising</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>


    <script src="~/Scripts/jquery-2.0.3.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>